import { NextRequest, NextResponse } from "next/server";
import { DemoAnalysisProvider } from "@/lib/analysis/demo-provider";
import { MediaFile, AnalysisSignalType, TrustReport } from "@/lib/types";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/**
 * GET /api/analyze
 * Status & configuration check. Secrets are never exposed.
 */
export async function GET() {
  const isDemo = process.env.NEXT_PUBLIC_DEMO_MODE !== "false";
  const hasPythonBackend = Boolean(process.env.PYTHON_BACKEND_URL);
  const hasTrustLayerApi = Boolean(process.env.TRUSTLAYER_API_URL);

  return NextResponse.json({
    service: "TrustLayer Analysis Gateway",
    version: "2.4.0",
    environment: process.env.NODE_ENV,
    mode: isDemo ? "DEMO_MODE" : "LIVE_MODE",
    provider: isDemo ? "DemoAnalysisProvider (Deterministic)" : "Live Microservice Gateway",
    configuredServices: {
      pythonBackend: hasPythonBackend,
      trustLayerApi: hasTrustLayerApi,
      c2paService: Boolean(process.env.C2PA_SERVICE_URL),
      metadataService: Boolean(process.env.METADATA_SERVICE_URL),
    },
    demoNotice: isDemo
      ? "DEMO ANALYSIS: Output generated by deterministic rules. No benchmark claims."
      : undefined,
  });
}

/**
 * POST /api/analyze
 * Server-side analysis gateway. Keeps external API keys and Python backend
 * credentials secure from client inspection. Fully Netlify serverless compatible.
 */
export async function POST(req: NextRequest) {
  try {
    const isDemo = process.env.NEXT_PUBLIC_DEMO_MODE !== "false";
    const pythonBackendUrl = process.env.PYTHON_BACKEND_URL;
    const trustlayerApiUrl = process.env.TRUSTLAYER_API_URL;
    const trustlayerApiKey = process.env.TRUSTLAYER_API_KEY;

    // Parse incoming multipart or JSON payload
    const contentType = req.headers.get("content-type") || "";
    let action = "analyze-media";
    let mediaMetadata: Partial<MediaFile> = {};
    let activeSignals: AnalysisSignalType[] = ["ai-detection", "provenance", "metadata", "forensic"];
    let fileBlob: Blob | null = null;
    let fileName = "uploaded-media";

    if (contentType.includes("multipart/form-data")) {
      const formData = await req.formData();
      action = (formData.get("action") as string) || "analyze-media";

      const metaRaw = formData.get("mediaMetadata") as string | null;
      if (metaRaw) {
        try {
          mediaMetadata = JSON.parse(metaRaw);
        } catch {
          // fallback
        }
      }

      const signalsRaw = formData.get("activeSignals") as string | null;
      if (signalsRaw) {
        try {
          activeSignals = JSON.parse(signalsRaw);
        } catch {
          // fallback
        }
      }

      const file = formData.get("file");
      if (file && typeof file !== "string") {
        fileBlob = file;
        fileName = file.name || "media-sample";
      }
    } else if (contentType.includes("application/json")) {
      const json = await req.json();
      action = json.action || "analyze-media";
      mediaMetadata = json.mediaMetadata || {};
      activeSignals = json.activeSignals || activeSignals;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // LIVE BACKEND ROUTING (When live mode is enabled and backend is configured)
    // ─────────────────────────────────────────────────────────────────────────
    if (!isDemo && (pythonBackendUrl || trustlayerApiUrl)) {
      const upstreamUrl = pythonBackendUrl || trustlayerApiUrl!;
      try {
        const upstreamFormData = new FormData();
        upstreamFormData.append("action", action);
        upstreamFormData.append("activeSignals", JSON.stringify(activeSignals));
        upstreamFormData.append("metadata", JSON.stringify(mediaMetadata));
        if (fileBlob) {
          upstreamFormData.append("file", fileBlob, fileName);
        }

        const headers: Record<string, string> = {};
        if (trustlayerApiKey) {
          headers["Authorization"] = `Bearer ${trustlayerApiKey}`;
        }

        const upstreamRes = await fetch(`${upstreamUrl}/verify`, {
          method: "POST",
          headers,
          body: upstreamFormData,
        });

        if (upstreamRes.ok) {
          const upstreamData = await upstreamRes.json();
          return NextResponse.json(upstreamData);
        } else {
          console.warn(
            `Upstream backend (${upstreamUrl}) returned error ${upstreamRes.status}. Falling back to demo provider.`
          );
        }
      } catch (upstreamErr) {
        console.error("Failed communicating with upstream backend:", upstreamErr);
      }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // DEMO PROVIDER EXECUTION (Default & Safe Fallback)
    // ─────────────────────────────────────────────────────────────────────────
    const demoProvider = new DemoAnalysisProvider();

    // Handle individual component analysis methods
    if (action === "analyze-image") {
      const sampleBlob = fileBlob || new Blob([""], { type: "image/jpeg" });
      const result = await demoProvider.analyzeImage(sampleBlob);
      return NextResponse.json(result);
    }

    if (action === "analyze-video") {
      const sampleBlob = fileBlob || new Blob([""], { type: "video/mp4" });
      const result = await demoProvider.analyzeVideo(sampleBlob);
      return NextResponse.json(result);
    }

    if (action === "analyze-metadata") {
      const sampleBlob = fileBlob || new Blob([""], { type: "application/octet-stream" });
      const result = await demoProvider.analyzeMetadata(sampleBlob);
      return NextResponse.json(result);
    }

    if (action === "analyze-provenance") {
      const sampleBlob = fileBlob || new Blob([""], { type: "application/octet-stream" });
      const result = await demoProvider.analyzeProvenance(sampleBlob);
      return NextResponse.json(result);
    }

    if (action === "analyze-forensics") {
      const sampleBlob = fileBlob || new Blob([""], { type: "image/jpeg" });
      const result = await demoProvider.analyzeForensics(sampleBlob);
      return NextResponse.json(result);
    }

    // Default: End-to-end media analysis
    const media: MediaFile = {
      id: mediaMetadata.id || `media-${Date.now().toString(36)}`,
      name: mediaMetadata.name || fileName,
      size: mediaMetadata.size || (fileBlob ? fileBlob.size : 1024 * 512),
      type: mediaMetadata.type || (fileBlob ? fileBlob.type : "image/jpeg"),
      extension: mediaMetadata.extension || fileName.split(".").pop()?.toUpperCase() || "JPG",
      mediaKind: mediaMetadata.mediaKind || (fileName.toLowerCase().endsWith(".mp4") || fileName.toLowerCase().endsWith(".mov") ? "video" : "image"),
      previewUrl: mediaMetadata.previewUrl || "",
      width: mediaMetadata.width || 1024,
      height: mediaMetadata.height || 1024,
      duration: mediaMetadata.duration,
      hashSha256: mediaMetadata.hashSha256 || "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    };

    const report = await demoProvider.analyzeMedia(media, activeSignals);
    return NextResponse.json(report);
  } catch (err: unknown) {
    console.error("API route /api/analyze error:", err);
    return NextResponse.json(
      {
        error: "Internal verification gateway error",
        message: err instanceof Error ? err.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
