import {
  MediaFile,
  AnalysisSignalType,
  TrustReport,
  EvidenceItem,
  EvidenceTimelineItem,
} from "@/lib/types";
import { AnalysisProvider } from "./provider";
import {
  AnalysisOptions,
  ImageAnalysisResult,
  VideoAnalysisResult,
  MetadataAnalysisResult,
  ProvenanceAnalysisResult,
  ForensicsAnalysisResult,
} from "./types";
import { defaultAnalysisService, AnalysisProgress } from "@/lib/services/analysisService";

/**
 * DemoAnalysisProvider
 *
 * Generates deterministic example results for prototype and demonstration purposes.
 * IMPORTANT: Every result is internally stamped with DEMO ANALYSIS markers.
 * Fictional benchmark accuracies are strictly avoided.
 */
export class DemoAnalysisProvider implements AnalysisProvider {
  readonly name = "DemoAnalysisProvider (DEMO ANALYSIS)";
  readonly isDemo = true;

  async analyzeMedia(
    media: MediaFile,
    activeSignals: AnalysisSignalType[],
    options?: AnalysisOptions
  ): Promise<TrustReport> {
    // Forward through deterministic analysis service with telemetry callbacks
    const report = await defaultAnalysisService.analyze(
      media,
      activeSignals,
      (progress: AnalysisProgress) => {
        if (options?.onProgress) {
          options.onProgress({
            stageIndex: progress.stageIndex,
            stageNumber: progress.stage.number,
            stageName: progress.stage.name,
            stageStatus: progress.stageStatus,
            qualitativeState: progress.stageStates[progress.stage.id]?.qualitativeState,
            telemetry: `[DEMO ANALYSIS] ${progress.telemetry}`,
            percentage: progress.percentage,
            completedStages: progress.completedStages,
            evidenceSignalsCollected: progress.evidenceSignalsCollected,
            totalSignals: progress.totalSignals,
          });
        }
      }
    );

    // Tag the report internally as DEMO ANALYSIS
    return {
      ...report,
      id: `${report.id}-demo`,
      reportReferenceId: `${report.reportReferenceId}-DEMO`,
      verdictTitle: `${report.verdictTitle} (DEMO ANALYSIS)`,
      keyFindings: [
        "[DEMO ANALYSIS] Findings produced by deterministic demo provider. No live AI model invoked.",
        ...report.keyFindings,
      ],
      disclaimer: `${report.disclaimer} Note: This assessment was generated by TrustLayer's DemoAnalysisProvider for evaluation purposes.`,
    };
  }

  async analyzeImage(file: File | Blob, options?: AnalysisOptions): Promise<ImageAnalysisResult> {
    return {
      isAiGenerated: true,
      signalStrength: "strong",
      confidenceLabel: "Strong",
      detectedIndicators: [
        "High-frequency discrete cosine transform grid attenuation",
        "Spatial boundary gradient falloff without optical depth of field",
      ],
      frequencyAnomaliesDetected: true,
      boundaryInconsistencies: true,
      modelIdentifier: "TrustLayer Ensemble-DF v2.4 (DEMO ANALYSIS)",
      analysisScope: "Dual-domain frequency analysis and spatial edge gradients",
      limitations: "AI detection is probabilistic and may perform differently on unseen generation methods.",
      items: [
        {
          id: "demo-image-indicator-1",
          signalId: "ai-detection",
          title: "Frequency Grid Discrepancy",
          summary: "Periodic sub-band artifacts characteristic of diffusion upsampling.",
          strength: "strong",
          confidence: 85,
          technicalData: {
            "Mode": "DEMO ANALYSIS",
            "Spectral Kurtosis": 4.12,
          },
        },
      ],
      isDemo: true,
    };
  }

  async analyzeVideo(file: File | Blob, options?: AnalysisOptions): Promise<VideoAnalysisResult> {
    return {
      isAiGenerated: false,
      signalStrength: "moderate",
      confidenceLabel: "Moderate",
      detectedIndicators: [
        "Inter-frame motion flow vectors consistent with nominal optical capture",
      ],
      temporalCoherenceScore: 88,
      faceWarpingDetected: false,
      frameInconsistencies: false,
      audioVideoSyncOffsetMs: 12,
      keyframesSampled: 5,
      modelIdentifier: "TrustLayer Video-Temporal v1.8 (DEMO ANALYSIS)",
      limitations: "Video temporal analysis is probabilistic and may be degraded by high bitrate compression.",
      items: [],
      isDemo: true,
    };
  }

  async analyzeMetadata(file: File | Blob): Promise<MetadataAnalysisResult> {
    return {
      status: "suspicious",
      confidenceLabel: "Moderate",
      exifPresent: true,
      containerMime: file.type || "application/octet-stream",
      softwareTag: "libvips / Composite Web Export (DEMO STAMP)",
      cameraMakeModel: "Stripped / Unspecified",
      quantizationProfileConsistent: false,
      timestampDeltaHours: 7.2,
      suspiciousFields: ["SoftwareTag", "MakerNotes", "QuantizationMatrix"],
      findings: [
        "Non-standard encoder signature detected in header block.",
        "Camera hardware serial stripped.",
      ],
      isDemo: true,
    };
  }

  async analyzeProvenance(file: File | Blob): Promise<ProvenanceAnalysisResult> {
    return {
      c2paStatus: "Not found",
      confidenceLabel: "Limited",
      jumbfBoxPresent: false,
      hasValidSignature: false,
      editHistoryAssertionsCount: 0,
      hardwareKeystoreVerified: false,
      summary: "No verifiable C2PA Content Credentials found in file headers.",
      policyNote: "Absence of C2PA provenance credentials does not mean the media is fake. Most consumer cameras and social media platforms do not attach credentials.",
      isDemo: true,
    };
  }

  async analyzeForensics(file: File | Blob): Promise<ForensicsAnalysisResult> {
    return {
      status: "detected",
      confidenceLabel: "Strong",
      elaVarianceDelta: 28.6,
      noiseFloorConsistent: false,
      lightingInconsistencyAngle: 18,
      edgeHaloDetected: true,
      anomalousQuadrants: [3],
      findings: [
        "Error Level Analysis reveals +28.6% delta clustering in foreground subject.",
        "Noise floor discontinuity observed across quadrant 3 boundary.",
      ],
      isDemo: true,
    };
  }
}
